services:
  static-web-client:
    build:
      context: ../applications/static-web-client
      dockerfile: Dockerfile
    ports:
      - 8080:80

  server:
    build:
      context: ../applications/server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
